//
//  PullRequestsJSON.swift
//  GitBuddyTests
//
//  Created by Antoine van der Lee on 10/01/2020.
//  Copyright © 2020 WeTransfer. All rights reserved.
//

import Foundation

let PullRequestsJSON = """

[{
        "url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50",
        "id": 359005203,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzU5MDA1MjAz",
        "html_url": "https://github.com/WeTransfer/Diagnostics/pull/50",
        "diff_url": "https://github.com/WeTransfer/Diagnostics/pull/50.diff",
        "patch_url": "https://github.com/WeTransfer/Diagnostics/pull/50.patch",
        "issue_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/50",
        "number": 50,
        "state": "closed",
        "locked": false,
        "title": "Add charset utf-8 to html head 😃",
        "user": {
            "login": "AvdLee",
            "id": 793147,
            "node_id": "MDQ6VXNlcjc5MzE0Nw==",
            "avatar_url": "https://avatars0.githubusercontent.com/u/793147?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AvdLee",
            "html_url": "https://github.com/AvdLee",
            "followers_url": "https://api.github.com/users/AvdLee/followers",
            "following_url": "https://api.github.com/users/AvdLee/following{/other_user}",
            "gists_url": "https://api.github.com/users/AvdLee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AvdLee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AvdLee/subscriptions",
            "organizations_url": "https://api.github.com/users/AvdLee/orgs",
            "repos_url": "https://api.github.com/users/AvdLee/repos",
            "events_url": "https://api.github.com/users/AvdLee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AvdLee/received_events",
            "type": "User",
            "site_admin": false
        },
        "body": "Non-ascii characters in HTML output were not displayed correctly in Safari. Specifying charset to utf-8 in HTML meta tag will fix this issue.",
        "created_at": "2020-01-03T14:22:35Z",
        "updated_at": "2020-01-06T12:46:36Z",
        "closed_at": "2020-01-06T12:46:36Z",
        "merged_at": "2020-01-06T12:46:35Z",
        "merge_commit_sha": "ada293ab4b12f6423da130edf37217d94ccf8148",
        "assignee": {
            "login": "kairadiagne",
            "id": 4329185,
            "node_id": "MDQ6VXNlcjQzMjkxODU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4329185?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/kairadiagne",
            "html_url": "https://github.com/kairadiagne",
            "followers_url": "https://api.github.com/users/kairadiagne/followers",
            "following_url": "https://api.github.com/users/kairadiagne/following{/other_user}",
            "gists_url": "https://api.github.com/users/kairadiagne/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/kairadiagne/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kairadiagne/subscriptions",
            "organizations_url": "https://api.github.com/users/kairadiagne/orgs",
            "repos_url": "https://api.github.com/users/kairadiagne/repos",
            "events_url": "https://api.github.com/users/kairadiagne/events{/privacy}",
            "received_events_url": "https://api.github.com/users/kairadiagne/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [{
            "login": "kairadiagne",
            "id": 4329185,
            "node_id": "MDQ6VXNlcjQzMjkxODU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4329185?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/kairadiagne",
            "html_url": "https://github.com/kairadiagne",
            "followers_url": "https://api.github.com/users/kairadiagne/followers",
            "following_url": "https://api.github.com/users/kairadiagne/following{/other_user}",
            "gists_url": "https://api.github.com/users/kairadiagne/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/kairadiagne/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kairadiagne/subscriptions",
            "organizations_url": "https://api.github.com/users/kairadiagne/orgs",
            "repos_url": "https://api.github.com/users/kairadiagne/repos",
            "events_url": "https://api.github.com/users/kairadiagne/events{/privacy}",
            "received_events_url": "https://api.github.com/users/kairadiagne/received_events",
            "type": "User",
            "site_admin": false
        }],
        "requested_reviewers": [

        ],
        "requested_teams": [

        ],
        "labels": [

        ],
        "milestone": null,
        "commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50/commits",
        "review_comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50/comments",
        "review_comment_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/50/comments",
        "statuses_url": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/6c695a40f809fdf80e5522e92b4ded1903a42097",
        "head": {
            "label": "AvdLee:charset-in-html",
            "ref": "charset-in-html",
            "sha": "6c695a40f809fdf80e5522e92b4ded1903a42097",
            "user": {
                "login": "AvdLee",
                "id": 793147,
                "node_id": "MDQ6VXNlcjc5MzE0Nw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/793147?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/AvdLee",
                "html_url": "https://github.com/AvdLee",
                "followers_url": "https://api.github.com/users/AvdLee/followers",
                "following_url": "https://api.github.com/users/AvdLee/following{/other_user}",
                "gists_url": "https://api.github.com/users/AvdLee/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/AvdLee/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/AvdLee/subscriptions",
                "organizations_url": "https://api.github.com/users/AvdLee/orgs",
                "repos_url": "https://api.github.com/users/AvdLee/repos",
                "events_url": "https://api.github.com/users/AvdLee/events{/privacy}",
                "received_events_url": "https://api.github.com/users/AvdLee/received_events",
                "type": "User",
                "site_admin": false
            },
            "repo": null
        },
        "base": {
            "label": "WeTransfer:master",
            "ref": "master",
            "sha": "f67a18ae2aa208fd94178b729e5dced0e56eac77",
            "user": {
                "login": "WeTransfer",
                "id": 14807662,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/WeTransfer",
                "html_url": "https://github.com/WeTransfer",
                "followers_url": "https://api.github.com/users/WeTransfer/followers",
                "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                "repos_url": "https://api.github.com/users/WeTransfer/repos",
                "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "repo": {
                "id": 225350163,
                "node_id": "MDEwOlJlcG9zaXRvcnkyMjUzNTAxNjM=",
                "name": "Diagnostics",
                "full_name": "WeTransfer/Diagnostics",
                "private": false,
                "owner": {
                    "login": "WeTransfer",
                    "id": 14807662,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/WeTransfer",
                    "html_url": "https://github.com/WeTransfer",
                    "followers_url": "https://api.github.com/users/WeTransfer/followers",
                    "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                    "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                    "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                    "repos_url": "https://api.github.com/users/WeTransfer/repos",
                    "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/WeTransfer/Diagnostics",
                "description": "Allow users to easily share Diagnostics with your support team to improve the flow of fixing bugs.",
                "fork": false,
                "url": "https://api.github.com/repos/WeTransfer/Diagnostics",
                "forks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/forks",
                "keys_url": "https://api.github.com/repos/WeTransfer/Diagnostics/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/WeTransfer/Diagnostics/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/WeTransfer/Diagnostics/teams",
                "hooks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/hooks",
                "issue_events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/events{/number}",
                "events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/events",
                "assignees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/assignees{/user}",
                "branches_url": "https://api.github.com/repos/WeTransfer/Diagnostics/branches{/branch}",
                "tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/tags",
                "blobs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/WeTransfer/Diagnostics/languages",
                "stargazers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/stargazers",
                "contributors_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contributors",
                "subscribers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscribers",
                "subscription_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscription",
                "commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contents/{+path}",
                "compare_url": "https://api.github.com/repos/WeTransfer/Diagnostics/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/WeTransfer/Diagnostics/merges",
                "archive_url": "https://api.github.com/repos/WeTransfer/Diagnostics/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/WeTransfer/Diagnostics/downloads",
                "issues_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues{/number}",
                "pulls_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/WeTransfer/Diagnostics/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/WeTransfer/Diagnostics/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/WeTransfer/Diagnostics/labels{/name}",
                "releases_url": "https://api.github.com/repos/WeTransfer/Diagnostics/releases{/id}",
                "deployments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/deployments",
                "created_at": "2019-12-02T10:43:07Z",
                "updated_at": "2020-01-16T02:01:31Z",
                "pushed_at": "2020-01-06T12:46:36Z",
                "git_url": "git://github.com/WeTransfer/Diagnostics.git",
                "ssh_url": "git@github.com:WeTransfer/Diagnostics.git",
                "clone_url": "https://github.com/WeTransfer/Diagnostics.git",
                "svn_url": "https://github.com/WeTransfer/Diagnostics",
                "homepage": null,
                "size": 2118,
                "stargazers_count": 377,
                "watchers_count": 377,
                "language": "Swift",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "forks_count": 20,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 3,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz"
                },
                "forks": 20,
                "open_issues": 3,
                "watchers": 377,
                "default_branch": "master"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50"
            },
            "html": {
                "href": "https://github.com/WeTransfer/Diagnostics/pull/50"
            },
            "issue": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/50"
            },
            "comments": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/50/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/50/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/6c695a40f809fdf80e5522e92b4ded1903a42097"
            }
        },
        "author_association": "CONTRIBUTOR"
    },
    {
        "url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49",
        "id": 358972101,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzU4OTcyMTAx",
        "html_url": "https://github.com/WeTransfer/Diagnostics/pull/49",
        "diff_url": "https://github.com/WeTransfer/Diagnostics/pull/49.diff",
        "patch_url": "https://github.com/WeTransfer/Diagnostics/pull/49.patch",
        "issue_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/49",
        "number": 49,
        "state": "closed",
        "locked": false,
        "title": "Fix warning occurring in pod library because of importing style.css #trivial",
        "user": {
            "login": "AvdLee",
            "id": 4329185,
            "node_id": "MDQ6VXNlcjQzMjkxODU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4329185?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AvdLee",
            "html_url": "https://github.com/AvdLee",
            "followers_url": "https://api.github.com/users/AvdLee/followers",
            "following_url": "https://api.github.com/users/AvdLee/following{/other_user}",
            "gists_url": "https://api.github.com/users/AvdLee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AvdLee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AvdLee/subscriptions",
            "organizations_url": "https://api.github.com/users/AvdLee/orgs",
            "repos_url": "https://api.github.com/users/AvdLee/repos",
            "events_url": "https://api.github.com/users/AvdLee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AvdLee/received_events",
            "type": "User",
            "site_admin": false
        },
        "body": "Fixes #39",
        "created_at": "2020-01-03T12:24:16Z",
        "updated_at": "2020-01-03T13:03:00Z",
        "closed_at": "2020-01-03T13:02:59Z",
        "merged_at": "2020-01-03T13:02:59Z",
        "merge_commit_sha": "fa4827ff14a3f9db52cb6bf133c1e7796335aa09",
        "assignee": {
            "login": "AvdLee",
            "id": 4329185,
            "node_id": "MDQ6VXNlcjQzMjkxODU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4329185?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AvdLee",
            "html_url": "https://github.com/AvdLee",
            "followers_url": "https://api.github.com/users/AvdLee/followers",
            "following_url": "https://api.github.com/users/AvdLee/following{/other_user}",
            "gists_url": "https://api.github.com/users/AvdLee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AvdLee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AvdLee/subscriptions",
            "organizations_url": "https://api.github.com/users/AvdLee/orgs",
            "repos_url": "https://api.github.com/users/AvdLee/repos",
            "events_url": "https://api.github.com/users/AvdLee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AvdLee/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [{
            "login": "AvdLee",
            "id": 4329185,
            "node_id": "MDQ6VXNlcjQzMjkxODU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4329185?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AvdLee",
            "html_url": "https://github.com/AvdLee",
            "followers_url": "https://api.github.com/users/AvdLee/followers",
            "following_url": "https://api.github.com/users/AvdLee/following{/other_user}",
            "gists_url": "https://api.github.com/users/AvdLee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AvdLee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AvdLee/subscriptions",
            "organizations_url": "https://api.github.com/users/AvdLee/orgs",
            "repos_url": "https://api.github.com/users/AvdLee/repos",
            "events_url": "https://api.github.com/users/AvdLee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AvdLee/received_events",
            "type": "User",
            "site_admin": false
        }],
        "requested_reviewers": [

        ],
        "requested_teams": [

        ],
        "labels": [

        ],
        "milestone": null,
        "commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49/commits",
        "review_comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49/comments",
        "review_comment_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/49/comments",
        "statuses_url": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/f0e8bd17cff045a8670a35410bb8b211237786f1",
        "head": {
            "label": "WeTransfer:feature/39-pod-warning-fix",
            "ref": "feature/39-pod-warning-fix",
            "sha": "f0e8bd17cff045a8670a35410bb8b211237786f1",
            "user": {
                "login": "WeTransfer",
                "id": 14807662,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/WeTransfer",
                "html_url": "https://github.com/WeTransfer",
                "followers_url": "https://api.github.com/users/WeTransfer/followers",
                "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                "repos_url": "https://api.github.com/users/WeTransfer/repos",
                "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "repo": {
                "id": 225350163,
                "node_id": "MDEwOlJlcG9zaXRvcnkyMjUzNTAxNjM=",
                "name": "Diagnostics",
                "full_name": "WeTransfer/Diagnostics",
                "private": false,
                "owner": {
                    "login": "WeTransfer",
                    "id": 14807662,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/WeTransfer",
                    "html_url": "https://github.com/WeTransfer",
                    "followers_url": "https://api.github.com/users/WeTransfer/followers",
                    "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                    "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                    "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                    "repos_url": "https://api.github.com/users/WeTransfer/repos",
                    "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/WeTransfer/Diagnostics",
                "description": "Allow users to easily share Diagnostics with your support team to improve the flow of fixing bugs.",
                "fork": false,
                "url": "https://api.github.com/repos/WeTransfer/Diagnostics",
                "forks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/forks",
                "keys_url": "https://api.github.com/repos/WeTransfer/Diagnostics/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/WeTransfer/Diagnostics/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/WeTransfer/Diagnostics/teams",
                "hooks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/hooks",
                "issue_events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/events{/number}",
                "events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/events",
                "assignees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/assignees{/user}",
                "branches_url": "https://api.github.com/repos/WeTransfer/Diagnostics/branches{/branch}",
                "tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/tags",
                "blobs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/WeTransfer/Diagnostics/languages",
                "stargazers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/stargazers",
                "contributors_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contributors",
                "subscribers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscribers",
                "subscription_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscription",
                "commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contents/{+path}",
                "compare_url": "https://api.github.com/repos/WeTransfer/Diagnostics/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/WeTransfer/Diagnostics/merges",
                "archive_url": "https://api.github.com/repos/WeTransfer/Diagnostics/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/WeTransfer/Diagnostics/downloads",
                "issues_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues{/number}",
                "pulls_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/WeTransfer/Diagnostics/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/WeTransfer/Diagnostics/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/WeTransfer/Diagnostics/labels{/name}",
                "releases_url": "https://api.github.com/repos/WeTransfer/Diagnostics/releases{/id}",
                "deployments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/deployments",
                "created_at": "2019-12-02T10:43:07Z",
                "updated_at": "2020-01-16T02:01:31Z",
                "pushed_at": "2020-01-06T12:46:36Z",
                "git_url": "git://github.com/WeTransfer/Diagnostics.git",
                "ssh_url": "git@github.com:WeTransfer/Diagnostics.git",
                "clone_url": "https://github.com/WeTransfer/Diagnostics.git",
                "svn_url": "https://github.com/WeTransfer/Diagnostics",
                "homepage": null,
                "size": 2118,
                "stargazers_count": 377,
                "watchers_count": 377,
                "language": "Swift",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "forks_count": 20,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 3,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz"
                },
                "forks": 20,
                "open_issues": 3,
                "watchers": 377,
                "default_branch": "master"
            }
        },
        "base": {
            "label": "WeTransfer:master",
            "ref": "master",
            "sha": "464db9ef3a7459c664db82f254e69479afb236be",
            "user": {
                "login": "WeTransfer",
                "id": 14807662,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/WeTransfer",
                "html_url": "https://github.com/WeTransfer",
                "followers_url": "https://api.github.com/users/WeTransfer/followers",
                "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                "repos_url": "https://api.github.com/users/WeTransfer/repos",
                "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "repo": {
                "id": 225350163,
                "node_id": "MDEwOlJlcG9zaXRvcnkyMjUzNTAxNjM=",
                "name": "Diagnostics",
                "full_name": "WeTransfer/Diagnostics",
                "private": false,
                "owner": {
                    "login": "WeTransfer",
                    "id": 14807662,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0ODA3NjYy",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/14807662?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/WeTransfer",
                    "html_url": "https://github.com/WeTransfer",
                    "followers_url": "https://api.github.com/users/WeTransfer/followers",
                    "following_url": "https://api.github.com/users/WeTransfer/following{/other_user}",
                    "gists_url": "https://api.github.com/users/WeTransfer/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/WeTransfer/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/WeTransfer/subscriptions",
                    "organizations_url": "https://api.github.com/users/WeTransfer/orgs",
                    "repos_url": "https://api.github.com/users/WeTransfer/repos",
                    "events_url": "https://api.github.com/users/WeTransfer/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/WeTransfer/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/WeTransfer/Diagnostics",
                "description": "Allow users to easily share Diagnostics with your support team to improve the flow of fixing bugs.",
                "fork": false,
                "url": "https://api.github.com/repos/WeTransfer/Diagnostics",
                "forks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/forks",
                "keys_url": "https://api.github.com/repos/WeTransfer/Diagnostics/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/WeTransfer/Diagnostics/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/WeTransfer/Diagnostics/teams",
                "hooks_url": "https://api.github.com/repos/WeTransfer/Diagnostics/hooks",
                "issue_events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/events{/number}",
                "events_url": "https://api.github.com/repos/WeTransfer/Diagnostics/events",
                "assignees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/assignees{/user}",
                "branches_url": "https://api.github.com/repos/WeTransfer/Diagnostics/branches{/branch}",
                "tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/tags",
                "blobs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/WeTransfer/Diagnostics/languages",
                "stargazers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/stargazers",
                "contributors_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contributors",
                "subscribers_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscribers",
                "subscription_url": "https://api.github.com/repos/WeTransfer/Diagnostics/subscription",
                "commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/WeTransfer/Diagnostics/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/WeTransfer/Diagnostics/contents/{+path}",
                "compare_url": "https://api.github.com/repos/WeTransfer/Diagnostics/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/WeTransfer/Diagnostics/merges",
                "archive_url": "https://api.github.com/repos/WeTransfer/Diagnostics/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/WeTransfer/Diagnostics/downloads",
                "issues_url": "https://api.github.com/repos/WeTransfer/Diagnostics/issues{/number}",
                "pulls_url": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/WeTransfer/Diagnostics/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/WeTransfer/Diagnostics/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/WeTransfer/Diagnostics/labels{/name}",
                "releases_url": "https://api.github.com/repos/WeTransfer/Diagnostics/releases{/id}",
                "deployments_url": "https://api.github.com/repos/WeTransfer/Diagnostics/deployments",
                "created_at": "2019-12-02T10:43:07Z",
                "updated_at": "2020-01-16T02:01:31Z",
                "pushed_at": "2020-01-06T12:46:36Z",
                "git_url": "git://github.com/WeTransfer/Diagnostics.git",
                "ssh_url": "git@github.com:WeTransfer/Diagnostics.git",
                "clone_url": "https://github.com/WeTransfer/Diagnostics.git",
                "svn_url": "https://github.com/WeTransfer/Diagnostics",
                "homepage": null,
                "size": 2118,
                "stargazers_count": 377,
                "watchers_count": 377,
                "language": "Swift",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "forks_count": 20,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 3,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz"
                },
                "forks": 20,
                "open_issues": 3,
                "watchers": 377,
                "default_branch": "master"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49"
            },
            "html": {
                "href": "https://github.com/WeTransfer/Diagnostics/pull/49"
            },
            "issue": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/49"
            },
            "comments": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/issues/49/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/pulls/49/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/WeTransfer/Diagnostics/statuses/f0e8bd17cff045a8670a35410bb8b211237786f1"
            }
        },
        "author_association": "MEMBER"
    }
]

"""
